### ISSUE TITLE
need help creating a custom mode 

### ISSUE THREAD

**Issue by siduck** [TimTinkers/rofi-iwd-menu#1]
Hi @TimTinkers . How do I use the script for a custom mode? like ( combi : "mymode:scriptpath") . I tried this but it says "dont run rofi inside rofi" . I understand that the script works standalone but it'd be nice if there would be a mode for this! Idk scripting :(

![image](https://user-images.githubusercontent.com/59060246/132780726-fe00958c-ff5a-4aa8-8c5d-5e24025c5c39.png)

**Comment by TimTinkers** [comment]
Hi @siduck! I've not had time to look into, check in, or otherwise maintain this script in a good while. I'm afraid I can't really help because I'm barely familiar with how I implemented this in the first place. I'm afraid you'll have to find a better resource for learning rofi than this project. I'm going to close this issue for now since it doesn't seem to be a problem with the script itself.
